spring:
#  h2:
#    console:
#    enabled: true
#    path: /h2-console

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver #org.h2.Driver
    url: jdbc:p6spy:h2:tcp://localhost/~/querydsl
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        show_sql: true


logging:
  level:
    org.hibernate.sql: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true